services:
  # PostgreSQL database for Vinci development
  postgres:
    restart: always
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: vinci_dev
      POSTGRES_USER: vinci_user
      POSTGRES_PASSWORD: vinci_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vinci_user -d vinci_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
